"""add_review_log

Revision ID: 807fb9322110
Revises: 53a3a7b588f7
Create Date: 2026-05-21 08:30:00.256077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '807fb9322110'
down_revision: Union[str, Sequence[str], None] = '53a3a7b588f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('card_id', sa.UUID(), nullable=False),
    sa.Column('deck_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False, comment='1: Again, 2: Hard, 3: Good, 4: Easy'),
    sa.Column('review_datetime', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('next_review_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('interval', sa.Float(), nullable=False, comment='Интервал в днях после ревью'),
    sa.Column('review_duration', sa.Integer(), nullable=True, comment='Длительность ревью в миллисекундах'),
    sa.Column('previous_stability', sa.Float(), nullable=False, comment='Стабильность до ревью'),
    sa.Column('previous_difficulty', sa.Float(), nullable=False, comment='Сложность до ревью'),
    sa.Column('new_stability', sa.Float(), nullable=False, comment='Стабильность после ревью'),
    sa.Column('new_difficulty', sa.Float(), nullable=False, comment='Сложность после ревью'),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['deck_id'], ['decks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_logs_card_id'), 'review_logs', ['card_id'], unique=False)
    op.create_index(op.f('ix_review_logs_deck_id'), 'review_logs', ['deck_id'], unique=False)
    op.create_index(op.f('ix_review_logs_rating'), 'review_logs', ['rating'], unique=False)
    op.create_index(op.f('ix_review_logs_review_datetime'), 'review_logs', ['review_datetime'], unique=False)
    op.create_index(op.f('ix_review_logs_user_id'), 'review_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_logs_user_id'), table_name='review_logs')
    op.drop_index(op.f('ix_review_logs_review_datetime'), table_name='review_logs')
    op.drop_index(op.f('ix_review_logs_rating'), table_name='review_logs')
    op.drop_index(op.f('ix_review_logs_deck_id'), table_name='review_logs')
    op.drop_index(op.f('ix_review_logs_card_id'), table_name='review_logs')
    op.drop_table('review_logs')
    # ### end Alembic commands ###
