"""decks cards fix fk 2

Revision ID: 6f98ffe937eb
Revises: 52d6c34f313b
Create Date: 2026-02-16 13:53:03.124228

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "6f98ffe937eb"
down_revision: Union[str, Sequence[str], None] = "52d6c34f313b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "decks",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["user_id"], ["user_profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_decks_name"), "decks", ["name"], unique=False)
    op.create_index(op.f("ix_decks_user_id"), "decks", ["user_id"], unique=False)
    op.create_table(
        "cards",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("deck_id", sa.UUID(), nullable=False),
        sa.Column("front", sa.String(length=512), nullable=False),
        sa.Column("back", sa.Text(), nullable=False),
        sa.Column(
            "fsrs_state",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("next_due", sa.DateTime(timezone=True), nullable=False),
        sa.Column("difficulty", sa.Float(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["deck_id"], ["decks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_cards_deck_id"), "cards", ["deck_id"], unique=False)
    op.create_index(op.f("ix_cards_difficulty"), "cards", ["difficulty"], unique=False)
    op.create_index(op.f("ix_cards_next_due"), "cards", ["next_due"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_cards_next_due"), table_name="cards")
    op.drop_index(op.f("ix_cards_difficulty"), table_name="cards")
    op.drop_index(op.f("ix_cards_deck_id"), table_name="cards")
    op.drop_table("cards")
    op.drop_index(op.f("ix_decks_user_id"), table_name="decks")
    op.drop_index(op.f("ix_decks_name"), table_name="decks")
    op.drop_table("decks")
    # ### end Alembic commands ###
