"""добавил таблицу user stats

Revision ID: 74aed3ef51f9
Revises: 7b13cfaef313
Create Date: 2026-06-01 05:37:24.613899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74aed3ef51f9'
down_revision: Union[str, Sequence[str], None] = '7b13cfaef313'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_stats',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('current_days_streak', sa.Integer(), server_default='0', nullable=False),
    sa.Column('max_days_streak', sa.Integer(), server_default='0', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_stats')
    # ### end Alembic commands ###
