"""изменение схем под новый формат

Revision ID: e1c6d06d4c2a
Revises: fcea70700f81
Create Date: 2026-08-24 06:43:32.470359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e1c6d06d4c2a'
down_revision: Union[str, Sequence[str], None] = 'fcea70700f81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # --- cards table ---
    op.add_column('cards', sa.Column('title', sa.String(length=512), nullable=True))
    op.execute("UPDATE cards SET title = '' WHERE title IS NULL")
    op.alter_column('cards', 'title', nullable=False)

    op.add_column('cards', sa.Column('hint1', sa.String(length=512), nullable=True))
    op.add_column('cards', sa.Column('hint2', sa.String(length=512), nullable=True))

    # Use raw SQL for JSONB conversion to avoid auto-cast error
    op.execute("ALTER TABLE cards ALTER COLUMN front TYPE JSONB USING front::jsonb")
    op.execute("ALTER TABLE cards ALTER COLUMN back TYPE JSONB USING back::jsonb")

    op.create_index(op.f('ix_cards_hint1'), 'cards', ['hint1'], unique=False)
    op.create_index(op.f('ix_cards_hint2'), 'cards', ['hint2'], unique=False)
    op.create_index(op.f('ix_cards_title'), 'cards', ['title'], unique=False)

    # --- cloud_card_templates table ---
    op.add_column('cloud_card_templates', sa.Column('title', sa.String(length=512), nullable=True))
    op.execute("UPDATE cloud_card_templates SET title = '' WHERE title IS NULL")
    op.alter_column('cloud_card_templates', 'title', nullable=False)

    op.add_column('cloud_card_templates', sa.Column('hint1', sa.Text(), nullable=True))
    op.add_column('cloud_card_templates', sa.Column('hint2', sa.Text(), nullable=True))

    op.execute("ALTER TABLE cloud_card_templates ALTER COLUMN front TYPE JSONB USING front::jsonb")
    op.execute("ALTER TABLE cloud_card_templates ALTER COLUMN back TYPE JSONB USING back::jsonb")

    op.create_index(op.f('ix_cloud_card_templates_title'), 'cloud_card_templates', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cloud_card_templates_title'), table_name='cloud_card_templates')
    op.drop_column('cloud_card_templates', 'hint2')
    op.drop_column('cloud_card_templates', 'hint1')
    op.drop_column('cloud_card_templates', 'title')
    op.execute("ALTER TABLE cloud_card_templates ALTER COLUMN back TYPE TEXT USING back::text")
    op.execute("ALTER TABLE cloud_card_templates ALTER COLUMN front TYPE TEXT USING front::text")
    op.drop_index(op.f('ix_cards_title'), table_name='cards')
    op.drop_index(op.f('ix_cards_hint2'), table_name='cards')
    op.drop_index(op.f('ix_cards_hint1'), table_name='cards')
    op.execute("ALTER TABLE cards ALTER COLUMN back TYPE TEXT USING back::text")
    op.execute("ALTER TABLE cards ALTER COLUMN front TYPE VARCHAR(512) USING front::varchar(512)")
    op.drop_column('cards', 'hint2')
    op.drop_column('cards', 'hint1')
    op.drop_column('cards', 'title')
    # ### end Alembic commands ###
