"""добавил поля downloaded and total_reviews в модели

Revision ID: 2993e49314d9
Revises: 0fb0c41004e2
Create Date: 2026-06-21 08:45:28.952234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2993e49314d9'
down_revision: Union[str, Sequence[str], None] = '0fb0c41004e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cloud_decks', sa.Column('downloaded', sa.Integer(), server_default='0', nullable=False, comment='Количество скачиваний колоды другими пользователями'))
    op.add_column('user_stats', sa.Column('total_reviews', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_stats', 'total_reviews')
    op.drop_column('cloud_decks', 'downloaded')
    # ### end Alembic commands ###
