"""добавил 2 новые таблицы клауд дек и кард а так же обновил существующие

Revision ID: 576666211033
Revises: 807fb9322110
Create Date: 2026-05-29 07:16:31.388249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '576666211033'
down_revision: Union[str, Sequence[str], None] = '807fb9322110'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cloud_decks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.String(length=10), server_default='PRIVATE', nullable=False),
    sa.Column('is_approved', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cloud_decks_author_id'), 'cloud_decks', ['author_id'], unique=False)
    op.create_index(op.f('ix_cloud_decks_is_approved'), 'cloud_decks', ['is_approved'], unique=False)
    op.create_index(op.f('ix_cloud_decks_name'), 'cloud_decks', ['name'], unique=False)
    op.create_index(op.f('ix_cloud_decks_type'), 'cloud_decks', ['type'], unique=False)
    op.create_table('cloud_card_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cloud_deck_id', sa.UUID(), nullable=False),
    sa.Column('front', sa.Text(), nullable=False),
    sa.Column('back', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cloud_deck_id'], ['cloud_decks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cloud_card_templates_cloud_deck_id'), 'cloud_card_templates', ['cloud_deck_id'], unique=False)
    op.add_column('cards', sa.Column('card_template_id', sa.UUID(), nullable=True))
    op.add_column('cards', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.create_index(op.f('ix_cards_card_template_id'), 'cards', ['card_template_id'], unique=False)
    op.create_index(op.f('ix_cards_is_deleted'), 'cards', ['is_deleted'], unique=False)
    op.create_foreign_key(None, 'cards', 'cloud_card_templates', ['card_template_id'], ['id'], ondelete='SET NULL')
    op.add_column('decks', sa.Column('cloud_deck_id', sa.UUID(), nullable=True))
    op.add_column('decks', sa.Column('is_cloud_deck', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('decks', sa.Column('cloud_type', sa.String(length=10), nullable=True))
    op.add_column('decks', sa.Column('is_approved', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('decks', sa.Column('author_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_decks_author_id'), 'decks', ['author_id'], unique=False)
    op.create_index(op.f('ix_decks_cloud_deck_id'), 'decks', ['cloud_deck_id'], unique=False)
    op.create_index(op.f('ix_decks_cloud_type'), 'decks', ['cloud_type'], unique=False)
    op.create_foreign_key(None, 'decks', 'user_profiles', ['author_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'decks', 'cloud_decks', ['cloud_deck_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'decks', type_='foreignkey')
    op.drop_constraint(None, 'decks', type_='foreignkey')
    op.drop_index(op.f('ix_decks_cloud_type'), table_name='decks')
    op.drop_index(op.f('ix_decks_cloud_deck_id'), table_name='decks')
    op.drop_index(op.f('ix_decks_author_id'), table_name='decks')
    op.drop_column('decks', 'author_id')
    op.drop_column('decks', 'is_approved')
    op.drop_column('decks', 'cloud_type')
    op.drop_column('decks', 'is_cloud_deck')
    op.drop_column('decks', 'cloud_deck_id')
    op.drop_constraint(None, 'cards', type_='foreignkey')
    op.drop_index(op.f('ix_cards_is_deleted'), table_name='cards')
    op.drop_index(op.f('ix_cards_card_template_id'), table_name='cards')
    op.drop_column('cards', 'is_deleted')
    op.drop_column('cards', 'card_template_id')
    op.drop_index(op.f('ix_cloud_card_templates_cloud_deck_id'), table_name='cloud_card_templates')
    op.drop_table('cloud_card_templates')
    op.drop_index(op.f('ix_cloud_decks_type'), table_name='cloud_decks')
    op.drop_index(op.f('ix_cloud_decks_name'), table_name='cloud_decks')
    op.drop_index(op.f('ix_cloud_decks_is_approved'), table_name='cloud_decks')
    op.drop_index(op.f('ix_cloud_decks_author_id'), table_name='cloud_decks')
    op.drop_table('cloud_decks')
    # ### end Alembic commands ###
