"""описание

Revision ID: b3594af49a79
Revises: e1c6d06d4c2a
Create Date: 2026-08-28 10:48:18.647409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b3594af49a79'
down_revision: Union[str, Sequence[str], None] = 'e1c6d06d4c2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('is_suspended', sa.Boolean(), server_default='false', nullable=False))
    op.create_index(op.f('ix_cards_is_suspended'), 'cards', ['is_suspended'], unique=False)
    op.drop_column('cards', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_cards_is_suspended'), table_name='cards')
    op.drop_column('cards', 'is_suspended')
    # ### end Alembic commands ###
