"""описания измнения

Revision ID: 090aea76dec7
Revises: 00619b0049bc
Create Date: 2026-02-24 16:28:35.590661

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "090aea76dec7"
down_revision: Union[str, Sequence[str], None] = "00619b0049bc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("cards", sa.Column("stability", sa.Float(), nullable=True))
    op.create_index(op.f("ix_cards_stability"), "cards", ["stability"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_cards_stability"), table_name="cards")
    op.drop_column("cards", "stability")
    # ### end Alembic commands ###
