"""Создание таблицы user_profiles

Revision ID: e84d73279050
Revises:
Create Date: 2026-02-08 19:47:23.875005

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "e84d73279050"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
