"""описание

Revision ID: 5519816d9d77
Revises: 5665d95499f9
Create Date: 2026-08-09 19:04:43.871878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5519816d9d77'
down_revision: Union[str, Sequence[str], None] = '5665d95499f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_analyses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('deck_id', sa.UUID(), nullable=True),
    sa.Column('analysis_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('stats_json', sa.Text(), nullable=False),
    sa.Column('analysis_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_analyses_analysis_date'), 'ai_analyses', ['analysis_date'], unique=False)
    op.create_index(op.f('ix_ai_analyses_deck_id'), 'ai_analyses', ['deck_id'], unique=False)
    op.create_index(op.f('ix_ai_analyses_user_id'), 'ai_analyses', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_analyses_user_id'), table_name='ai_analyses')
    op.drop_index(op.f('ix_ai_analyses_deck_id'), table_name='ai_analyses')
    op.drop_index(op.f('ix_ai_analyses_analysis_date'), table_name='ai_analyses')
    op.drop_table('ai_analyses')
    # ### end Alembic commands ###
