"""Добавил поля для синхранизации

Revision ID: 5a57e2d74a1b
Revises: 2993e49314d9
Create Date: 2026-06-23 19:03:56.910648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a57e2d74a1b'
down_revision: Union[str, Sequence[str], None] = '2993e49314d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cloud_decks', sa.Column('last_synced_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('decks', sa.Column('last_synced_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('decks', 'last_synced_at')
    op.drop_column('cloud_decks', 'last_synced_at')
    # ### end Alembic commands ###
