"""добавил таймзон к юзеру

Revision ID: fcea70700f81
Revises: f9ae57a4ab95
Create Date: 2026-08-12 18:06:26.338706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcea70700f81'
down_revision: Union[str, Sequence[str], None] = 'f9ae57a4ab95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('timezone_str', sa.String(length=50), server_default='UTC', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'timezone_str')
    # ### end Alembic commands ###
