"""описанияchange cards model

Revision ID: 00619b0049bc
Revises: 6f98ffe937eb
Create Date: 2026-02-17 16:17:11.674829

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "00619b0049bc"
down_revision: Union[str, Sequence[str], None] = "6f98ffe937eb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cards",
        sa.Column("in_learning", sa.Boolean(), server_default="false", nullable=False),
    )
    op.alter_column(
        "cards",
        "fsrs_state",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
        existing_server_default=sa.text("'{}'::jsonb"),
    )
    op.alter_column(
        "cards",
        "next_due",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
    )
    op.alter_column(
        "cards",
        "difficulty",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=True,
    )
    op.create_index(
        op.f("ix_cards_in_learning"), "cards", ["in_learning"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_cards_in_learning"), table_name="cards")
    op.alter_column(
        "cards",
        "difficulty",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False,
    )
    op.alter_column(
        "cards",
        "next_due",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
    )
    op.alter_column(
        "cards",
        "fsrs_state",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
        existing_server_default=sa.text("'{}'::jsonb"),
    )
    op.drop_column("cards", "in_learning")
    # ### end Alembic commands ###
