"""описание

Revision ID: 5665d95499f9
Revises: e451eed0cc93
Create Date: 2026-08-02 14:40:36.269157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5665d95499f9'
down_revision: Union[str, Sequence[str], None] = 'e451eed0cc93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cloud_decks', sa.Column('previous_authors', sa.ARRAY(sa.UUID()), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cloud_decks', 'previous_authors')
    # ### end Alembic commands ###
