"""add_new_field_to_deck

Revision ID: 53a3a7b588f7
Revises: 090aea76dec7
Create Date: 2026-05-13 07:06:42.045604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53a3a7b588f7'
down_revision: Union[str, Sequence[str], None] = '090aea76dec7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('decks', sa.Column('desired_retention', sa.Numeric(precision=3, scale=2), server_default='0.90', nullable=False, check_constraint='desired_retention BETWEEN 0.85 AND 0.95'))
    op.add_column('decks', sa.Column('maximum_interval', sa.Integer(), server_default='36500', nullable=False, check_constraint='maximum_interval BETWEEN 30 AND 99999'))
    op.add_column('decks', sa.Column('color', sa.String(length=7), server_default='#4A90E2', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('decks', 'color')
    op.drop_column('decks', 'maximum_interval')
    op.drop_column('decks', 'desired_retention')
    # ### end Alembic commands ###
