"""описание

Revision ID: e451eed0cc93
Revises: 5a57e2d74a1b
Create Date: 2026-08-01 19:33:46.030427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e451eed0cc93'
down_revision: Union[str, Sequence[str], None] = '5a57e2d74a1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('is_updated', sa.Boolean(), server_default='false', nullable=False))
    op.create_index(op.f('ix_cards_is_updated'), 'cards', ['is_updated'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cards_is_updated'), table_name='cards')
    op.drop_column('cards', 'is_updated')
    # ### end Alembic commands ###
